table shg_group_distribution_final
	lineageTag: 048b10c1-9d3d-4ecb-93d9-097f28e750c9

	column _id
		dataType: string
		lineageTag: e46ce811-ab05-4a0e-8792-838ea2860ea4
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column shg_name
		dataType: string
		lineageTag: 1cd1c3ed-19c2-4e43-8b46-0ebc5e0ca717
		summarizeBy: none
		sourceColumn: shg_name

		annotation SummarizationSetBy = Automatic

	column shg_id
		dataType: string
		lineageTag: 4cf9fcfb-9261-46c2-afa4-9ef88159fe54
		summarizeBy: none
		sourceColumn: shg_id

		annotation SummarizationSetBy = Automatic

	column shg_group_unit_received
		dataType: string
		lineageTag: cc3ef9a8-a175-483f-b320-4697e2bc3c1f
		summarizeBy: none
		sourceColumn: shg_group_unit_received

		annotation SummarizationSetBy = Automatic

	column shg_group_qty_received
		dataType: double
		lineageTag: caa59a2f-a690-4a2d-bb28-f0bb15cd9904
		summarizeBy: sum
		sourceColumn: shg_group_qty_received

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column __Submissions-id
		dataType: string
		lineageTag: 9a825692-df00-41db-8f53-d432fa76dc8c
		summarizeBy: none
		sourceColumn: __Submissions-id

		annotation SummarizationSetBy = Automatic

	column district
		dataType: string
		lineageTag: dfae1a6c-3437-483f-8524-dd4629d70fe7
		summarizeBy: none
		sourceColumn: district

		annotation SummarizationSetBy = Automatic

	column subcounty
		dataType: string
		lineageTag: 60bbf992-df50-4d0f-b101-434a6eb4b3fd
		summarizeBy: none
		sourceColumn: subcounty

		annotation SummarizationSetBy = Automatic

	column dateCreated
		dataType: dateTime
		formatString: General Date
		lineageTag: f2d72a36-3619-4e03-83a3-f73f4d784ee1
		summarizeBy: none
		sourceColumn: dateCreated

		variation Variation
			isDefault
			relationship: cfa255d6-58ba-46bd-8ecd-77cd94b46a28
			defaultHierarchy: LocalDateTable_0d429e11-6766-4688-a7ce-2a353823af94.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column lastUpdated
		dataType: dateTime
		formatString: General Date
		lineageTag: 6a28a5d1-6c38-4b7d-89fd-bc4a352348aa
		summarizeBy: none
		sourceColumn: lastUpdated

		variation Variation
			isDefault
			relationship: 1926fd03-ab34-49fd-abe2-9b34bbaaa23e
			defaultHierarchy: LocalDateTable_54880fab-75f2-4097-a848-b7e21f579d3c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column createdBy
		dataType: string
		lineageTag: 20042935-6755-49e0-9ee4-5488efc46e75
		summarizeBy: none
		sourceColumn: createdBy

		annotation SummarizationSetBy = Automatic

	column shgs_view_shg_id
		dataType: string
		lineageTag: de5737a3-6323-4571-98ea-b5632181739b
		summarizeBy: none
		sourceColumn: shgs_view_shg_id

		annotation SummarizationSetBy = Automatic

	column docId
		dataType: string
		lineageTag: f5c98f18-1905-46e3-ab5b-1464ac31b47b
		summarizeBy: none
		sourceColumn: docId

		annotation SummarizationSetBy = Automatic

	column partner
		dataType: string
		lineageTag: 037242ab-c566-40a3-9329-7050eb01c26e
		summarizeBy: none
		sourceColumn: partner

		annotation SummarizationSetBy = Automatic

	column district_name
		dataType: string
		lineageTag: e12156f1-4a3e-4891-8145-593f51b47ade
		summarizeBy: none
		sourceColumn: district_name

		annotation SummarizationSetBy = Automatic

	column material_type
		dataType: string
		lineageTag: c84f72e0-5594-4876-8a64-b94e5db55f7e
		summarizeBy: none
		sourceColumn: material_type

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 736cb925-e5c3-4a40-8440-23166bfd5ac1
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column distribution_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d54723e5-6422-4c3e-aa51-0130147a304a
		summarizeBy: none
		sourceColumn: distribution_date

		variation Variation
			isDefault
			relationship: ba934082-1fdb-445b-836d-709d2d02df6c
			defaultHierarchy: LocalDateTable_20a584a7-ff1d-4fe4-b16a-f918e6f6b20f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column participant_type
		dataType: string
		lineageTag: cb945962-9746-4a8f-a5ef-213370867ce6
		summarizeBy: none
		sourceColumn: participant_type

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: ba426038-9edd-4a82-8eb1-68d8ba57d4d8
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column submitterName
		dataType: string
		lineageTag: 6330accd-d41d-4c90-9c44-f96ebdf01398
		summarizeBy: none
		sourceColumn: submitterName

		annotation SummarizationSetBy = Automatic

	column submissionDate
		dataType: dateTime
		formatString: General Date
		lineageTag: ce30c14c-65c1-4707-8519-2557f356df22
		summarizeBy: none
		sourceColumn: submissionDate

		variation Variation
			isDefault
			relationship: aeec11fd-f560-46cf-b49e-2f4a376cca97
			defaultHierarchy: LocalDateTable_0b3b6d1f-daf6-4e83-a5ad-357405df08d7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column other_shg_group_unit_received
		dataType: string
		lineageTag: 2325fb20-9711-4077-b320-2825b87f7e9e
		summarizeBy: none
		sourceColumn: other_shg_group_unit_received

		annotation SummarizationSetBy = Automatic

	column shg_profiling_form_shg_id
		dataType: string
		lineageTag: 519f3b29-7436-41b9-9e81-b3c2c425ee4e
		summarizeBy: none
		sourceColumn: shg_profiling_form_shg_id

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.other_material_type'
		dataType: string
		lineageTag: 4bee9096-9ac0-44ce-a641-eb355e96e4b3
		summarizeBy: none
		sourceColumn: distribution_mainform.other_material_type

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.livestock_type'
		dataType: string
		lineageTag: d19e1c2f-2c0c-4ec4-ab58-838ed9adb7c6
		summarizeBy: none
		sourceColumn: distribution_mainform.livestock_type

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.other_livestock_type'
		dataType: string
		lineageTag: 6b0c8897-b65b-41ed-9021-1697c6f8944f
		summarizeBy: none
		sourceColumn: distribution_mainform.other_livestock_type

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.crop_type'
		dataType: string
		lineageTag: 1cf6ba23-184f-4b7b-a96d-2d8df1279d1c
		summarizeBy: none
		sourceColumn: distribution_mainform.crop_type

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.other_crop_type'
		dataType: string
		lineageTag: 633050b2-97b1-4a96-9361-84b2beb61126
		summarizeBy: none
		sourceColumn: distribution_mainform.other_crop_type

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.agri_resources_type'
		dataType: string
		lineageTag: 966686cb-7fea-47f3-b125-b4aa54e1c9ff
		summarizeBy: none
		sourceColumn: distribution_mainform.agri_resources_type

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.other_agri_resources_type'
		dataType: string
		lineageTag: d6dae761-a99c-449c-b88e-7886e74b778c
		summarizeBy: none
		sourceColumn: distribution_mainform.other_agri_resources_type

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.isla_kits'
		dataType: string
		lineageTag: cba8c472-a92a-4a87-a0a9-c0435434dd54
		summarizeBy: none
		sourceColumn: distribution_mainform.isla_kits

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.other_isla_kits'
		dataType: string
		lineageTag: 42a06be9-0ff4-4f81-85a8-c47971cab6db
		summarizeBy: none
		sourceColumn: distribution_mainform.other_isla_kits

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.unit'
		dataType: string
		lineageTag: fdfe8404-a25b-4db3-86e4-e6e9155bc783
		summarizeBy: none
		sourceColumn: distribution_mainform.unit

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_other'
		dataType: int64
		formatString: 0
		lineageTag: ebb95192-e40a-4b5e-b617-fd141d1b0dde
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_other

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_kgs'
		dataType: double
		lineageTag: aafc2b2e-fba8-46ea-b568-fe3922959521
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_kgs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'distribution_mainform.qty_distributed_grams'
		dataType: double
		lineageTag: 62417796-4b46-4837-90fc-834f35026bbf
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_grams

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'distribution_mainform.qty_distributed_seedlings'
		dataType: int64
		formatString: 0
		lineageTag: eb6a28ab-f43e-425a-bf49-9e44371fa31a
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_seedlings

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_liters'
		dataType: double
		lineageTag: 33b1da1c-fafd-4dd4-8bb0-858f9978f895
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_liters

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'distribution_mainform.qty_distributed_packets'
		dataType: int64
		formatString: 0
		lineageTag: 3d43a5ca-73f4-4960-8428-953d4bea6515
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_packets

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_dozens'
		dataType: string
		lineageTag: 95e6ad98-b04c-40d3-885e-fabd6236a1b7
		summarizeBy: none
		sourceColumn: distribution_mainform.qty_distributed_dozens

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_sackets'
		dataType: double
		lineageTag: 60746ed6-bc7a-4d62-b074-521caa214e20
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_sackets

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'distribution_mainform.qty_distributed_tins'
		dataType: double
		lineageTag: b902aa20-89ff-44cf-8268-d9af669d4ac4
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_tins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'distribution_mainform.qty_distributed_boxes'
		dataType: string
		lineageTag: f0f5b4f2-842c-4dba-aafd-3c7299755537
		summarizeBy: none
		sourceColumn: distribution_mainform.qty_distributed_boxes

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_pieces'
		dataType: int64
		formatString: 0
		lineageTag: 2e71c446-1b46-4f0f-802c-25776e68a232
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_pieces

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_number'
		dataType: int64
		formatString: 0
		lineageTag: 2a11d388-70b7-4eee-a1de-08277311af54
		summarizeBy: sum
		sourceColumn: distribution_mainform.qty_distributed_number

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_kit'
		dataType: string
		lineageTag: 876daabf-e471-4c80-9bec-445207f819ce
		summarizeBy: none
		sourceColumn: distribution_mainform.qty_distributed_kit

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_meters'
		dataType: string
		lineageTag: 1b96ad89-f92a-4111-8a5c-7fcff2d836d8
		summarizeBy: none
		sourceColumn: distribution_mainform.qty_distributed_meters

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_hectare'
		dataType: string
		lineageTag: 4cd118be-bd68-4722-a0ba-12d6421ff70b
		summarizeBy: none
		sourceColumn: distribution_mainform.qty_distributed_hectare

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_acre'
		dataType: string
		lineageTag: a165765b-babc-4609-ba7d-29ca9228a8cb
		summarizeBy: none
		sourceColumn: distribution_mainform.qty_distributed_acre

		annotation SummarizationSetBy = Automatic

	column 'distribution_mainform.qty_distributed_foot'
		dataType: string
		lineageTag: d97863c7-028c-4787-b393-197bcb965900
		summarizeBy: none
		sourceColumn: distribution_mainform.qty_distributed_foot

		annotation SummarizationSetBy = Automatic

	partition shg_group_distribution_final = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(#"shg_group distribution", {"__Submissions-id"}, distribution_mainform, {"_id"}, "distribution_mainform", JoinKind.LeftOuter),
				    #"Expanded distribution_mainform" = Table.ExpandTableColumn(Source, "distribution_mainform", {"other_material_type", "livestock_type", "other_livestock_type", "crop_type", "other_crop_type", "agri_resources_type", "other_agri_resources_type", "isla_kits", "other_isla_kits", "unit", "qty_distributed_other", "qty_distributed_kgs", "qty_distributed_grams", "qty_distributed_seedlings", "qty_distributed_liters", "qty_distributed_packets", "qty_distributed_dozens", "qty_distributed_sackets", "qty_distributed_tins", "qty_distributed_boxes", "qty_distributed_pieces", "qty_distributed_number", "qty_distributed_kit", "qty_distributed_meters", "qty_distributed_hectare", "qty_distributed_acre", "qty_distributed_foot"}, {"distribution_mainform.other_material_type", "distribution_mainform.livestock_type", "distribution_mainform.other_livestock_type", "distribution_mainform.crop_type", "distribution_mainform.other_crop_type", "distribution_mainform.agri_resources_type", "distribution_mainform.other_agri_resources_type", "distribution_mainform.isla_kits", "distribution_mainform.other_isla_kits", "distribution_mainform.unit", "distribution_mainform.qty_distributed_other", "distribution_mainform.qty_distributed_kgs", "distribution_mainform.qty_distributed_grams", "distribution_mainform.qty_distributed_seedlings", "distribution_mainform.qty_distributed_liters", "distribution_mainform.qty_distributed_packets", "distribution_mainform.qty_distributed_dozens", "distribution_mainform.qty_distributed_sackets", "distribution_mainform.qty_distributed_tins", "distribution_mainform.qty_distributed_boxes", "distribution_mainform.qty_distributed_pieces", "distribution_mainform.qty_distributed_number", "distribution_mainform.qty_distributed_kit", "distribution_mainform.qty_distributed_meters", "distribution_mainform.qty_distributed_hectare", "distribution_mainform.qty_distributed_acre", "distribution_mainform.qty_distributed_foot"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded distribution_mainform",{{"distribution_date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"distribution_date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

